#!/bin/bash
# CortexDB Launch Script — TCC workaround (launchd can't exec from ~/Documents)
# Called by ai.shre.cortexdb.plist with KeepAlive enabled
#
# Starts all CortexDB services via Docker Compose and monitors the router.
# If the router exits, this script exits non-zero → launchd restarts it.
# Detects port conflicts and finds alternative ports if needed.
set -euo pipefail

CORTEXDB_DIR="/Users/aibot/Documents/Projects/shreai/cortexdb"
LOG_DIR="/Users/aibot/.shre/logs"
DOCKER="/usr/local/bin/docker"

# Default ports
ROUTER_PORT=5400
HEALTH_PORT=5401
ADMIN_PORT=5402
PG_PORT=5433
QDRANT_PORT=6333
REDIS_PORT=6379
REDIS_STREAM_PORT=6380

mkdir -p "$LOG_DIR"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_DIR/cortexdb-boot.log"; }

# ── Port Conflict Detection ──────────────────────────────────────────────────

check_port() {
    local port=$1
    local service=$2
    local pid

    pid=$(lsof -ti :"$port" 2>/dev/null | head -1)
    if [ -n "$pid" ]; then
        local proc_name
        proc_name=$(ps -p "$pid" -o comm= 2>/dev/null || echo "unknown")

        # If it's our own Docker process, that's fine
        if echo "$proc_name" | grep -qiE "docker|com.docker"; then
            return 0
        fi

        log "PORT CONFLICT: port $port needed by $service is in use by $proc_name (PID $pid)"
        echo "$pid"
        return 1
    fi
    return 0
}

find_free_port() {
    local base_port=$1
    local max_offset=20
    for offset in $(seq 0 $max_offset); do
        local candidate=$((base_port + offset))
        if ! lsof -ti :"$candidate" > /dev/null 2>&1; then
            echo "$candidate"
            return 0
        fi
    done
    return 1
}

resolve_port_conflicts() {
    local conflicts=0
    local port_map=""

    # Check each CortexDB port
    for pair in \
        "$ROUTER_PORT:router" \
        "$HEALTH_PORT:health" \
        "$ADMIN_PORT:admin" \
        "$PG_PORT:postgres" \
        "$QDRANT_PORT:qdrant" \
        "$REDIS_PORT:redis" \
        "$REDIS_STREAM_PORT:redis-stream"; do

        local port="${pair%%:*}"
        local svc="${pair##*:}"

        if ! check_port "$port" "$svc" > /dev/null 2>&1; then
            conflicts=$((conflicts + 1))
            local new_port
            new_port=$(find_free_port "$port")
            if [ -n "$new_port" ] && [ "$new_port" != "$port" ]; then
                log "PORT REMAP: $svc $port → $new_port"
                port_map="${port_map}${svc}:${port}:${new_port}\n"

                # Update the port variable for health checks later
                case "$svc" in
                    router) ROUTER_PORT=$new_port ;;
                    health) HEALTH_PORT=$new_port ;;
                    admin)  ADMIN_PORT=$new_port ;;
                esac
            else
                log "ERROR: Cannot find free port near $port for $svc"
                return 1
            fi
        fi
    done

    if [ "$conflicts" -eq 0 ]; then
        log "Port check passed — all ports available"
        return 0
    fi

    # Generate override docker-compose with remapped ports
    local override_file="$CORTEXDB_DIR/docker-compose.port-override.yml"
    log "Generating port override: $override_file"

    cat > "$override_file" << YAML
# Auto-generated by cortexdb-start.sh — port conflict resolution
# $(date '+%Y-%m-%d %H:%M:%S')
services:
YAML

    echo -e "$port_map" | while IFS=: read -r svc old_port new_port; do
        [ -z "$svc" ] && continue
        case "$svc" in
            router)
                cat >> "$override_file" << YAML
  cortex-router:
    ports:
      - "${new_port}:5400"
YAML
                ;;
            health)
                cat >> "$override_file" << YAML
  cortex-router:
    ports:
      - "${new_port}:5401"
YAML
                ;;
            postgres)
                cat >> "$override_file" << YAML
  relational-core:
    ports:
      - "127.0.0.1:${new_port}:5432"
YAML
                ;;
            qdrant)
                cat >> "$override_file" << YAML
  vector-core:
    ports:
      - "127.0.0.1:${new_port}:6333"
YAML
                ;;
            redis)
                cat >> "$override_file" << YAML
  memory-core:
    ports:
      - "127.0.0.1:${new_port}:6379"
YAML
                ;;
            redis-stream)
                cat >> "$override_file" << YAML
  stream-core:
    ports:
      - "127.0.0.1:${new_port}:6380"
YAML
                ;;
        esac
    done

    # Write active port map for other services to discover
    local port_file="$LOG_DIR/cortexdb-ports.env"
    cat > "$port_file" << EOF
# CortexDB active ports — auto-generated $(date '+%Y-%m-%d %H:%M:%S')
CORTEXDB_ROUTER_PORT=$ROUTER_PORT
CORTEXDB_HEALTH_PORT=$HEALTH_PORT
CORTEXDB_ADMIN_PORT=$ADMIN_PORT
EOF
    log "Active ports written to $port_file"

    # Use override file
    export COMPOSE_FILE="docker-compose.yml:docker-compose.port-override.yml"
    return 0
}

# ── Main ─────────────────────────────────────────────────────────────────────

log "CortexDB starting..."

# Wait for Docker Desktop to be ready
for i in $(seq 1 60); do
    if "$DOCKER" info > /dev/null 2>&1; then
        log "Docker ready"
        break
    fi
    if [ "$i" -eq 60 ]; then
        log "ERROR: Docker not available after 60s"
        exit 1
    fi
    sleep 1
done

cd "$CORTEXDB_DIR"

# Check and resolve port conflicts before starting
resolve_port_conflicts || {
    log "FATAL: Unresolvable port conflicts — cannot start"
    exit 1
}

# Start all services
"$DOCKER" compose up -d 2>&1 | tee -a "$LOG_DIR/cortexdb-boot.log"

# Wait for router health
for i in $(seq 1 60); do
    if curl -sf "http://localhost:${ROUTER_PORT}/health/live" > /dev/null 2>&1; then
        log "CortexDB router healthy on port $ROUTER_PORT"
        break
    fi
    if [ "$i" -eq 60 ]; then
        log "WARNING: Router not healthy after 60s, continuing to monitor"
    fi
    sleep 1
done

log "CortexDB all services up — entering monitor loop (router on :${ROUTER_PORT})"

# Monitor loop: check router health every 30s, exit if container dies
# (launchd KeepAlive will restart this script, which restarts everything)
while true; do
    sleep 30

    # Check if router container is running
    if ! "$DOCKER" compose ps cortex-router --format '{{.State}}' 2>/dev/null | grep -q "running"; then
        log "ERROR: cortex-router container not running — attempting restart"
        "$DOCKER" compose up -d cortex-router 2>&1 | tee -a "$LOG_DIR/cortexdb-boot.log"
        sleep 10

        if ! "$DOCKER" compose ps cortex-router --format '{{.State}}' 2>/dev/null | grep -q "running"; then
            log "ERROR: cortex-router failed to restart — exiting for launchd restart"
            exit 1
        fi
    fi

    # Health check
    if ! curl -sf "http://localhost:${ROUTER_PORT}/health/live" > /dev/null 2>&1; then
        log "WARNING: health check failed on :${ROUTER_PORT}, router may be restarting"
    fi
done
